version: "3"
services: 
  app_container:
    container_name: voicemod-challenge
    restart: always
    build: .
    links:
      - postgres
    depends_on:
      - postgres
      - redis
    ports: 
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: voicemod-challenge-db
    networks:
      - app-network
  
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network

networks:
  app-network:
    driver: bridge